# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  codex-proxy = {
    pname = "codex-proxy";
    version = "aa8d9032ff92ae984482f44818b509f72cd0d7b2";
    src = fetchFromGitHub {
      owner = "jmmaloney4";
      repo = "codex-proxy";
      rev = "aa8d9032ff92ae984482f44818b509f72cd0d7b2";
      fetchSubmodules = false;
      sha256 = "sha256-q1UE3cCFsGqOdd4aljVX1QBw4zmVMEJnKcACigfHy64=";
    };
    date = "2026-06-02";
  };
  gemini-proxy = {
    pname = "gemini-proxy";
    version = "5f701a244ed3c4699e6c1b0550bd50e961601ebe";
    src = fetchFromGitHub {
      owner = "KashifKhn";
      repo = "gemini-proxy";
      rev = "5f701a244ed3c4699e6c1b0550bd50e961601ebe";
      fetchSubmodules = false;
      sha256 = "sha256-RYDeVd66AXHHbm7TzX8et8QUspvfjxpkq8o4VXh76Cw=";
    };
    date = "2026-03-09";
  };
  mcp-ynab = {
    pname = "mcp-ynab";
    version = "b7b21e4990fa824b24bb86f2f2d8fd053817f047";
    src = fetchFromGitHub {
      owner = "jmmaloney4";
      repo = "mcp-ynab";
      rev = "b7b21e4990fa824b24bb86f2f2d8fd053817f047";
      fetchSubmodules = false;
      sha256 = "sha256-Ukh5FvBmk5A4ol2IRpBvrWp1K6fcWDfxssiw0gJ9l84=";
    };
    date = "2026-03-07";
  };
  nautilus-trader = {
    pname = "nautilus-trader";
    version = "1408bec68bb01ba1c3166e1f3803f1536fc9c950";
    src = fetchFromGitHub {
      owner = "nautechsystems";
      repo = "nautilus_trader";
      rev = "1408bec68bb01ba1c3166e1f3803f1536fc9c950";
      fetchSubmodules = false;
      sha256 = "sha256-5NgHvKZoydlqxfMvXEjZy73g8kJGoIV2L7kRKnfkRXc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-5NgHvKZoydlqxfMvXEjZy73g8kJGoIV2L7kRKnfkRXc=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-05-29";
  };
  spooktacular = {
    pname = "spooktacular";
    version = "f36634b84e1d38d81bd282b0f88a497557e4a520";
    src = fetchFromGitHub {
      owner = "Spooky-Labs";
      repo = "spooktacular";
      rev = "f36634b84e1d38d81bd282b0f88a497557e4a520";
      fetchSubmodules = false;
      sha256 = "sha256-x8bqwvbw0WZKASEIDqCVR8b91RqJKSLYcNSfe68WzrE=";
    };
    date = "2026-04-19";
  };
  tod = {
    pname = "tod";
    version = "v0.12.1";
    src = fetchFromGitHub {
      owner = "alanvardy";
      repo = "tod";
      rev = "v0.12.1";
      fetchSubmodules = false;
      sha256 = "sha256-091/1go/dBpTxK60Zh1cuzEJl7Fh7X7vpStRRoKFOzA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-091_1go_dBpTxK60Zh1cuzEJl7Fh7X7vpStRRoKFOzA=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
