# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nautilus-trader = {
    pname = "nautilus-trader";
    version = "9af16766e6ccd9cea6efb912689a7bf71260a141";
    src = fetchFromGitHub {
      owner = "nautechsystems";
      repo = "nautilus_trader";
      rev = "9af16766e6ccd9cea6efb912689a7bf71260a141";
      fetchSubmodules = false;
      sha256 = "sha256-2me7AL05hR11vfr4Km7qGbJfQwPCDWxMscMtTRN+UuY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-2me7AL05hR11vfr4Km7qGbJfQwPCDWxMscMtTRN+UuY=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-04-15";
  };
  openchamber = {
    pname = "openchamber";
    version = "v1.9.5";
    src = fetchFromGitHub {
      owner = "btriapitsyn";
      repo = "openchamber";
      rev = "v1.9.5";
      fetchSubmodules = false;
      sha256 = "sha256-rVVqQAVAmVKCLZOUCbp9OEtIY3RvHWYh3kG0fnmHktQ=";
    };
  };
  tod = {
    pname = "tod";
    version = "v0.11.2";
    src = fetchFromGitHub {
      owner = "alanvardy";
      repo = "tod";
      rev = "v0.11.2";
      fetchSubmodules = false;
      sha256 = "sha256-layx+AgcL1TPTh71Ef+Ej5JvzKjEV6Gl6S5Uoi82buA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-layx+AgcL1TPTh71Ef+Ej5JvzKjEV6Gl6S5Uoi82buA=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
