# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@lmstudio/lms-isomorphic-0.4.3" = {
      name = "_at_lmstudio_slash_lms-isomorphic";
      packageName = "@lmstudio/lms-isomorphic";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lmstudio/lms-isomorphic/-/lms-isomorphic-0.4.3.tgz";
        sha512 = "9SXSaLtxbU4Zx4XaB0SUX/76WkK3QaUHaz0iipk5NyTVqtZatRtBk9Eiq5oZlVaGt+vAc9O4bIL1jtBTA3U3wA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "bufferutil-4.0.9" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.9.tgz";
        sha512 = "WDtdLmJvAuNNPzByAYpRo2rF1Mmradw6gvWsQKf63476DDXmomT9zUiGypLcG4ibIM67vhAj8jJRdbmEws2Aqw==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "node-gyp-build-4.8.4" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.4.tgz";
        sha512 = "LA4ZjwlnUblHVgq0oBF3Jl/6h/Nvs5fzBLwdEF4nuxnFdsfajde4WfxtJr3CaiH+F6ewcIB/q4jQ4UzPyid+CQ==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "utf-8-validate-6.0.5" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "6.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-6.0.5.tgz";
        sha512 = "EYZR+OpIXp9Y1eG1iueg8KRsY8TuT8VNgnanZ0uA3STqhHQTLwbl+WX76/9X5OY12yQubymBpaBSmMPkSTQcKA==";
      };
    };
    "ws-8.18.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.18.0.tgz";
        sha512 = "8VbfWfHLbbwu3+N6OKsOMpBdT4kXPDDB9cJk2bJ6mh9ucxdlnNvH1e+roYkKmN9Nxw2yjz7VzeO9oOz2zJ04Pw==";
      };
    };
    "zod-3.24.1" = {
      name = "zod";
      packageName = "zod";
      version = "3.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-3.24.1.tgz";
        sha512 = "muH7gBL9sI1nciMZV67X5fTKKBLtwpZ5VBp1vsOQzj1MhrBZ4wlVCm3gedKZWLp0Oyel8sIGfeiz54Su+OVT+A==";
      };
    };
  };
in
{
  lms = nodeEnv.buildNodePackage {
    name = "lms";
    packageName = "lms";
    version = "0.0.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/lms/-/lms-0.0.9.tgz";
      sha512 = "edDQWwY++QPMcPcRU1tdu59kx1JezYy15+/29MPAd3z/JFyd9VloQB2bgvjhw47eT4iRjf6ghTUMT10AJaECVA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "See https://github.com/lmstudio-ai/lms for more information";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@lmstudio/sdk" = nodeEnv.buildNodePackage {
    name = "_at_lmstudio_slash_sdk";
    packageName = "@lmstudio/sdk";
    version = "0.4.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/@lmstudio/sdk/-/sdk-0.4.6.tgz";
      sha512 = "QH1iJN8VyCrotXXf4pfsh+IQr8w7lcWAC5ZrRo17EqnbePLpcLspjWDjYQaq6fO6sB5+8xvqJ1C62O+jTjPg3Q==";
    };
    dependencies = [
      sources."@lmstudio/lms-isomorphic-0.4.3"
      sources."ansi-styles-4.3.0"
      sources."bufferutil-4.0.9"
      sources."chalk-4.1.2"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."has-flag-4.0.0"
      sources."node-gyp-build-4.8.4"
      sources."supports-color-7.2.0"
      sources."utf-8-validate-6.0.5"
      sources."ws-8.18.0"
      sources."zod-3.24.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "LM Studio SDK";
      homepage = "https://github.com/lmstudio-ai/lmstudio.js#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
