name: 📌 add to project
on:
  issues:
    types: [opened, reopened, transferred, labeled]
  pull_request:
    types: [opened, reopened, labeled]
permissions:
  contents: read
jobs:
  add-to-project:
    uses: jmmaloney4/sector7/.github/workflows/add-to-project.yml@17768ae04fd2fe8eb2eeed56adfadb624cbc4f29 # main
