name: 📌 add to project
on:
  issues:
    types: [opened, reopened, transferred, labeled]
  pull_request:
    types: [opened, reopened, labeled]
permissions:
  contents: read
jobs:
  add-to-project:
    uses: jmmaloney4/sector7/.github/workflows/add-to-project.yml@716385280a47c6a26fa0bfe83bf2f165c61390f3 # main
