name: 📌 add to project
on:
  issues:
    types: [opened, reopened, transferred, labeled]
  pull_request:
    types: [opened, reopened, labeled]
permissions:
  contents: read
jobs:
  add-to-project:
    uses: jmmaloney4/sector7/.github/workflows/add-to-project.yml@30eadecf743fcf9815945b4b0b533e373c88ba1d # main
