name: 📝 adr
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/internal/designs/*.md'
permissions:
  contents: write
  pull-requests: write
jobs:
  adr-management:
    if: github.actor != 'github-actions[bot]'
    uses: jmmaloney4/sector7/.github/workflows/adr-management.yml@716385280a47c6a26fa0bfe83bf2f165c61390f3 # main
    with:
      runs-on: ubuntu-latest
      repository: ${{ github.repository }}
      ref: ${{ github.event.pull_request.head.sha }}
      base_ref: ${{ github.event.pull_request.base.ref }}
      adr_glob: 'docs/internal/designs/*.md'
      pr_number: ${{ github.event.pull_request.number }}
      pr_url: ${{ github.event.pull_request.html_url }}
