name: '❄️ nix'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  nix:
    uses: jmmaloney4/sector7/.github/workflows/nix.yml@c092e9e8950ea49c6938e1627ac3b98ce090fd0d # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
