name: '❄️ nix'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  nix:
    uses: jmmaloney4/sector7/.github/workflows/nix.yml@f3b121ecadfc01ec2c49907322dc2b4c24e80a8e # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
