name: '❄️ nix'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  nix:
    uses: jmmaloney4/toolbox/.github/workflows/nix.yml@e713ed4362a2948bda5642a42b2e2739f4962d71 # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
